# Generated by Django 5.0.4 on 2024-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vonty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_number',
            field=models.PositiveIntegerField(blank=True, help_text="Problem number of this problem in the contest/problem-set that it appeared in.Leave this blank for standalone problems, but it's always useful to keep a number for ordering problems.", null=True),
        ),
    ]
