# Generated by Django 5.0.4 on 2024-04-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vonty', '0002_problem_problem_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='filter_implies_parent',
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_number',
            field=models.PositiveIntegerField(blank=True, help_text="Problem number of this problem in the contest/problem-set that it appeared in. Leave this blank for standalone problems, but it's always useful to keep a number for ordering problems.", null=True),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(check=models.Q(('use_filter', False), ('parent__isnull', False), _connector='OR'), name='filter_implies_parent', violation_error_message='A tag meant to be used as a filter must have a parent tag.'),
        ),
    ]
