# Generated by Django 5.0.4 on 2024-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vonty_app', '0002_alter_tag_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(help_text='The list of tags associated with the problem.', related_name='problem_set', to='vonty_app.tag'),
        ),
    ]
