# Generated by Django 5.0.4 on 2024-04-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vonty', '0003_remove_tag_filter_implies_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='depth',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='path',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
