# Generated by Django 5.0.4 on 2024-04-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vonty_app', '0003_alter_problem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='desc',
            field=models.TextField(help_text='Optional longer description.', max_length=200),
        ),
    ]
