# Generated by Django 5.0.4 on 2024-04-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vonty', '0005_remove_tag_filter_implies_parent_remove_tag_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='desc',
            field=models.TextField(blank=True, help_text='Optional longer description.', max_length=200),
        ),
    ]
