# Generated by Django 5.0.4 on 2024-04-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vonty', '0006_alter_tag_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(help_text='Identifier slug. e.g. angle-chase', unique=True),
        ),
    ]
