# Generated by Django 5.0.4 on 2024-04-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vonty', '0007_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(help_text='Unique dentifier slug. e.g. angle-chase', unique=True),
        ),
    ]
