# Generated by Django 5.0.4 on 2024-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vonty', '0008_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The list of tags associated with the problem.', related_name='problem_set', to='vonty.tag'),
        ),
    ]
