# Generated by Django 5.0.4 on 2024-04-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vonty', '0009_alter_problem_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='path',
        ),
    ]
