# Generated by Django 5.0.4 on 2024-04-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vonty_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(help_text='The parent tag that this tag comes under.Filtering by the parent tag filters by this tag too.If this field is blank, the is_filter option must be unchecked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='vonty_app.tag'),
        ),
    ]
